[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
remappings = [
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "forge-std/=lib/forge-std/src/",
  "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "poseidon-solidity/=lib/poseidon-solidity/contracts/",
  "zk-kit.solidity/=lib/zk-kit.solidity/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@selfxyz/contracts/=lib/self/contracts/",
  "davinci-contracts/=lib/davinci-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
